### ISSUE TITLE
getrennte straßen sind mit fehlenden infos

### ISSUE THREAD

**Issue by joshinils** [britiger/openmaptiles-cycling-qa-deploy#3]
https://cycling-qa.lorenz.lu/#18.26/52.662056/13.28653
aufgespalten als zweimal oneway=yes, wegen verkehrsinsel(n) oder mittelstreifen.
dass bei oneway ein radweg gegenrichtung fehlt ist nicht so sonderlich wichtig (?)

**Comment by britiger** [comment]
Unabhängig von der Straße geht es ja um folgendes Tagging:
```
bicycle 	use_sidepath
cycleway:left 	no
cycleway:right 	separate
```
Das ist auch sehr häufig an Landstraßen so und ich bin noch am Knobeln wie ich das genau darstelle, wenn ich wie angekündigt die Fahrtrichtugen einzeln darstelle wäre 1 Seite grün die Andere rot. Sofern wie in diesem Fall `bicycle=use_sidepath` angegeben ist muss ein Radweg in beiden Richtungen genutzt werden, egal auf welcher Seite (Fahrtrichtung).

**Comment by joshinils** [comment]
genau, use_sidepath sollte angeben, dass in beide fahrtrichtungen ein separater radweg existiert und kartiert ist und man darüber routen sollte, da dieser rechtlich zu benutzen ist.

sonst wäre das bicycle:forward oder bicycle:backward=use_sidepath, was ich sehr selten benutze oder sehe (wenn überhaupt mal irgendwo)

streng genommen haben beide teile der straße für sich genommen keinen radweg in die andere richtung, aber so gesehen ist die straße auch eine einbahnstraße ohne dass sie von ihrer anderen seite irgendetwas weiß.

dabei fällt mir auch, dass das 
`cycleway:left=no`
`cycleway:right=separate`
erstmal keinerlei info darüber gibt in welche richtung man den rechts angelegten radweg nehmen darf, kann oder muss.

**Comment by britiger** [comment]
Ich habe das Styling auf 2 Spuren ergänzt, noch nicht aktiv würde dann jetzt wie folgt aussehen:

Vorher:
![screenshot](https://user-images.githubusercontent.com/2057760/182472621-9d9132dc-b4ba-43fc-b49c-6649fb86db85.png)

Nachher:
![screenshot2](https://user-images.githubusercontent.com/2057760/182472624-410e6131-9090-4248-8abc-13c6ce6fa01d.png)
