### ISSUE TITLE
Legende schwer lesbar

### ISSUE THREAD

**Issue by joshinils** [britiger/openmaptiles-cycling-qa-deploy#5]
Ich finde die einzelnen Linien zu dünn und somit scher schwer auseinander zu halten.
Die Linien in der Karte selber sind deutlich dicker und ich kann die Farben erkennen und unterscheiden.

Außerdem fehlen Beschreibungen für die gepunkteten und gestrichelten Linien

**Comment by britiger** [comment]
DIe Legende kommt aus 
https://github.com/watergis/maplibre-gl-legend 
Eine Beschreibung dazu gibt es jetzt hier:
https://github.com/britiger/openmaptiles-cycling-qa-deploy/blob/cl_twodirections/LEGEND.md

**Comment by britiger** [comment]
Wird mit #12 gelöst.
