### ISSUE TITLE
Bei Layer "zwei Wege" erscheinen Pop-ups manchmal doppelt

### ISSUE THREAD

**Issue by joshinils** [britiger/openmaptiles-cycling-qa-deploy#7]
![image](https://user-images.githubusercontent.com/34302971/183514291-e9b81d60-29e8-49f0-926c-a6b94f11b3b5.png)
https://cycling-qa.lorenz.lu/#19.66/52.6624124/13.3189797

ich kann erst eines, dann das andere weg-clicken mit dem 'X'

**Comment by britiger** [comment]
Habe Popup Inhalt aktualisiert, hab die Reproduktion des Fehlers nicht hin bekommen, hatte es aber auch schon mal. hängt dann damit zusammen, dass für eine weg mehrere Styles vorhanden sind.

**Comment by joshinils** [comment]
es muss schon das "zwei wege" layer ausgewählt sein, nicht das "default" layer.
dann kann ich bei dem pinken segment "zwischen" die linke und rechte spur klicken, dann erscheinen beide gleichzeitig
