### ISSUE TITLE
manche radwege nicht sichtbat

### ISSUE THREAD

**Issue by joshinils** [britiger/openmaptiles-cycling-qa-deploy#9]
ich weiß, du schließt viele straßen von vornherein aus.

aber an manchen dieser gibt es radwege oder andere infrastruktur.
magst du diese wiederum doch anzeigen?

denn das vorhandensein eines radwegs abseits von straßen zb fällt hierbei überhaupt nicht auf.
der mauerweg um berlin zb. wird deswegen nicht angezeigt.

oder was genau soll der zweck der karte sein, und fällt das nicht darunter?

oder dauert das filtern und anschließende auswerten doch zu lange?

wie lange braucht das jetzt überhaupt?

**Comment by britiger** [comment]
Radwege mit entsprechenden traffic_sign werden immer angezeigt. Werde Style ergänzen um alle Straßen anzuzeigen.
